### ISSUE TITLE
Mutabilidade de atributos de Clientes e Carros

### ISSUE THREAD

**Issue by jpastolfo** [jpastolfo/ADA-Locate-Car#18]
Os atributos Id, placa, cpf e cnpj precisam ser não mutáveis mesmo?

**Comment by PedroQueiroz1** [comment]
Então, sobre esse issue, que a gente discutiu pelo whatsapp, acredito que não terá como retirar os setters desses atributos pois não temos um banco de dados para ficar encarregado de settar os valores. 
Por conta disso, precisaremos dos setters mesmo para realizarmos os testes nas classes Terminais com os devidos valores.
